import Head from "next/head";
import { Layout } from "../components/Layout";

import { Pokemon } from "../interfaces/pokemon";
import { useMemo, useState } from "react";

const HomePage = ({ pokemons }: { pokemons: Pokemon[] }) => {
  const [filters, setFilters] = useState({
    name: "",
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;

    setFilters((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const filteredPokemon = useMemo(() => {
    return pokemons
      .filter((pokemon) => 
        pokemon.name.toLowerCase().includes(filters.name.toLocaleLowerCase())
      )
  }, [pokemons, filters.name])

  return (
    <>
      <Head>
        <title>Technical test next.js and typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pokemon list</h1>

      <div>
        <div>Search</div>
        <input
          type="text"
          placeholder="search by name"
          name="name"
          value={filters.name}
          onChange={(e) => handleInputChange(e)}
        />
        <div>Power threshold</div>
        <input type="text"></input>
        <div>Count over threshold: </div>
        <div>Min: </div>
        <div>Max: </div>
      </div>
      {filteredPokemon.map((pokemon) => (
        <div key={pokemon.id}>{pokemon.name}</div>
      ))}
    </>
  );
};

HomePage.getLayout = Layout;

export async function getStaticProps() {
  try {
    const pokemons = await fetch("http://localhost:3000/api/pokemons").then(
      (resp) => resp.json()
    );
    return { props: { pokemons } };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}

export default HomePage;
